apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "todo.fullname" . }}-{{ .Values.server.graphql.deployment.name }}"
spec:
  replicas: {{ .Values.server.graphql.deployment.replicaCount }}
  selector:
    matchLabels:
      name: "{{ include "todo.fullname" . }}-{{ .Values.server.graphql.deployment.name }}"
  template:
    metadata:
      labels:
        name: "{{ include "todo.fullname" . }}-{{ .Values.server.graphql.deployment.name }}"
    spec:
      containers:
        - name: "{{ .Chart.Name }}-{{ .Values.server.graphql.deployment.name }}"
          {{- if .Values.image }}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- else }}
          image: "{{ .Values.server.graphql.deployment.image.repository }}:{{ .Values.server.graphql.deployment.image.tag }}"
          imagePullPolicy: {{ .Values.server.graphql.deployment.imagePullPolicy }}
          {{- end }}
          ports:
              - containerPort: {{ .Values.server.graphql.port }}
          {{- if .Values.environment.development }} 
          env:
          - name: ENVIRONMENT
            value: "development"
          - name: PSQL_DB
            value: "{{ include "todo.fullname" . }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local"
          {{- end }}