apiVersion: v1
kind: Service
metadata:
  name: "{{ include "todo.fullname" . }}-{{ .Values.server.graphql.service.name }}"
spec:
  selector: 
    name: "{{ include "todo.fullname" . }}-{{ .Values.server.graphql.deployment.name }}"
  ports:
    - port: {{ .Values.server.graphql.port }}
      targetPort: {{ .Values.server.graphql.port }}