version: '3'
services:
  nginx: 
    image: nginx:latest
    volumes: 
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
    depends_on:
      - graphql
    
  graphql:
    image: iknowhtml/todo-graphql:${CURRENT_TAG}
    build:
      context: ./server/graphql
    working_dir: /usr/app