version: '2'
services:
  base:
    image: node:alpine
    volumes:
      - ./server/graphql:/usr/app
      - node_modules:/usr/app/node_modules
    working_dir: /usr/app
  install:
    extends:
      service: base
    command: yarn install

volumes:
  node_modules:
    external: true