version: '3'
services:
  nginx: 
    image: nginx:latest
    volumes: 
      - ./server/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
    depends_on:
      - graphql
    
  graphql:
    image: iknowhtml/todo-graphql:$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=2) | sed -n 1p)
    build:
      context: ./server/graphql
    working_dir: /usr/app