version: '3'
services:
  nginx: 
    image: nginx:latest
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80
    
  graphql:
    image: graphql
    build:
      context: ./server/graphql
    working_dir: /usr/app
    command: yarn start
    ports: 
      - 9090:9090
