version: '3'
services:
  nginx: 
    image: nginx:latest
    volumes: 
      - ./server/nginx/nginx.development.conf:/etc/nginx/nginx.conf
    ports: 
      - 3000:80
    
  graphql:
    image: node:alpine
    volumes:
      - ./server/graphql:/usr/app
      - node_modules:/usr/app/node_modules
    working_dir: /usr/app
    command: yarn start

volumes:
  node_modules:
    external: true