apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy: 
    sha256: {}
  artifacts:
    - image: iknowhtml/todo-graphql
      context: server/graphql
      docker: 
        dockerfile: Development.Dockerfile
      sync:
        infer:
        - 'src/**/*.js'
deploy:
    helm:
      releases:
        - name: todo
          chartPath: infrastructure/helm