apiVersion: skaffold/v1beta13
kind: Config
build:
  tagPolicy: 
    sha256: {}
  artifacts:
    - image: iknowhtml/todo/server/graphql
      context: server/graphql
      docker: 
        dockerfile: Development.Dockerfile
      sync:
        infer:
        - 'src/**/*.js'
deploy:
    helm:
      releases:
        - name: development
          chartPath: infrastructure/helm
          values:
            skaffold.server.graphql.deployment.image: iknowhtml/todo/server/graphql 
profiles: 
  - name: production
    build:
      tagPolicy:
        sha256:{}
      artifacts:
        - image: iknowhtml/todo/server/graphql
          context: server/graphql
    deploy:
      releases:
        - name: 
          chartPath: infrastructure/helm