apiVersion: skaffold/v2alpha1
kind: Config
build:
  tagPolicy: 
    sha256: {}
  artifacts:
    - image: iknowhtml/todo-graphql
      context: server/graphql
      docker: 
        dockerfile: Development.Dockerfile
      sync:
        infer:
        - 'src/**/*.js'
    - image: iknowhtml/todo-client
      context: client
      docker:
        dockerfile: Development.Dockerfile
      sync:
        infer:
        - 'src/**/*.js'
deploy:
  helm:
    releases:
    - name: todo
      chartPath: infrastructure/helm
      values:
        graphqlImage: iknowhtml/todo-graphql
        clientImage: iknowhtml/todo-client
    flags:
      upgrade:
        - --install