apiVersion: skaffold/v2alpha1
kind: Config
build:
  tagPolicy: 
    sha256: {}
  artifacts:
    - image: iknowhtml/todo-graphql
      context: server/graphql
      docker: 
        dockerfile: Development.Dockerfile
      sync:
        infer:
        - 'src/**/*.js'
deploy:
  helm:
    releases:
    - name: todo
      chartPath: infrastructure/helm
      valuesFiles:
      - skaffold-values.yaml
    flags:
      upgrade:
        - --install