apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ include "todo.fullname" . }}-ingress"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    {{- if .Values.environment.production }}
    cert-manager.io/issuer: "letsencrypt-prod"
    {{- end }}
spec:
  {{- if .Values.environment.production }}
  tls:
  - hosts:
    - todo.iknowht.ml
    secretName: todo-iknowht-ml-tls
  {{- end }}
  rules:
    {{- if .Values.environment.production }}
  - host: todo.iknowht.ml
    http:
    {{- else }}
  - http:
    {{- end }}
      paths:
        - path: /graphql
          backend:
            serviceName: {{ include "todo.fullname" . }}-{{ .Values.server.graphql.service.name }}
            servicePort: {{.Values.server.graphql.port}}