apiVersion: v1
kind: Service
metadata:
  name: "{{ include "todo.fullname" . }}-{{ .Values.client.service.name }}"
spec:
  selector: 
    name: "{{ include "todo.fullname" . }}-{{ .Values.client.deployment.name }}"
  ports:
    - port: {{ .Values.client.port }}
      targetPort: {{ .Values.client.port }}