version: 2
jobs:
  # Updates versions of services if applicable and pushes update with tag
  tag:
    branches:
      only: master
    working_directory: ~/todo
    docker:
      - image: circleci/node
    steps:
      # Checks out code from Github (1)
      - checkout
  build:
    branches:
      only: master
    filters:
      tags:
        only: /^v.*/
    working_directory: ~/todo
    docker:
      - image: circleci/node  
    steps:
      # (1)
      - checkout
      # Sets Up a Remote Environment to Execute Docker Commands (2)
      - setup_remote_docker
      - run:
          name: Install Docker Client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
  deploy:
    filters:
      tags: 
        only: /^v.*/
    requires:
      - build
    working directory: ~/todo
    docker:
      - image: docker:git
    steps:
      # (1)
      - checkout
      # (2)
      - setup_remote_docker 
