apiVersion: v1
kind: Service
metadata:
  name: "{{ include "todo.fullname" . }}-{{ .Values.server.graphql.clusterIPService.name }}"
spec:
  ports:
    - port: {{ .Values.server.graphql.port }}
      targetPort: {{ .Values.server.graphql.port }}
