{{- if .Values.production }}
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: iknowsmtp@gmail.com
        privateKeySecretRef:
            name: letsencrypt-prod
        solvers:
        - http01:
            ingress:
                class: nginx
{{- end }}