apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ include "todo.fullname" . }}-ingress"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /api/v1
            backend:
              serviceName: {{ include "todo.fullname" . }}-{{.Values.server.restAPI.clusterIPService.name}}
              servicePort: {{.Values.server.restAPI.port}}