server:
  restAPI:
    deployment:
      name: rest-api-deployment
      replicaCount: 1
      imagePullPolicy: Never
    clusterIPService:
      name: rest-api-cluster-ip-service
      type: ClusterIP
    port: 9090

nginx-ingress:
  defaultBackend:
    enabled: false


