environment:
  production: true
  development: false

server:
  graphql:
    deployment:
      name: graphql
      replicaCount: 1
      image:
        repository: iknowhtml/todo-graphql
        tag: latest
      imagePullPolicy: IfNotPresent
    clusterIPService:
      name: graphql-cluster-ip
    port: 9090