dependencies:
- name: nginx-ingress
  version: "1.26.2"
  repository: "https://kubernetes-charts.storage.googleapis.com/"
- name: cert-manager
  version: "v0.12.0"
  repository: "https://charts.jetstack.io"