server:
  graphql:
    deployment:
      name: graphql-deployment
      replicaCount: 1
      image:
        repository: iknowhtml/todo/server/graphql
        tag: latest
      imagePullPolicy: Never
    clusterIPService:
      name: graphql-cluster-ip-service
    port: 9090

nginx-ingress:
  defaultBackend:
    enabled: false


