server:
  restAPI:
    deployment:
      name: rest-api-deployment
      replicaCount: 1
      image:
        repository: iknowhtml/todo/server/rest-api
        tag: dev
      imagePullPolicy: Never
    clusterIPService:
      name: rest-api-cluster-ip-service
    port: 9090

nginx-ingress:
  defaultBackend:
    enabled: false


