# ENVIRONMENT CONFIGURATIONS FOR DEVELOPMENT
environment:
  production: false
  development: true

# SERVER CONFIGURATIONS
server:
  graphql:
    deployment:
      name: graphql-deployment
      replicaCount: 1
      image:
        repository: iknowhtml/todo-graphql
        tag: latest
      imagePullPolicy: ifNotPresent
    clusterIPService:
      name: graphql-cluster-ip-service
    port: 9090

# NGINX INGRESS CONFIGURATIONS
## NO HTTP LOAD BALANCING CONFIGURATION FOR NGINX INGRESS
controller:
  service:
    type: ClusterIP
  hostNetwork: true

## NO DEFAULT BACKEND
defaultBackend:
  enabled: false

# POSTGRESQL CONFIGURATIONS
global:
  postgresql:
    postgresqlUsername: user
    postgresqlPassword: password
initdbUsername: user
initdbPassword: password
initdbScripts:
  init.sql: |
    CREATE DATABASE todo;

    CREATE TABLE public.tasks
    (
        id serial,
        name text NOT NULL,
        completed boolean NOT NULL DEFAULT false,
        description text,
        due_date date,
        due_time time with time zone,
        location point,
        CONSTRAINT id_pk PRIMARY KEY (id)
    );

