environment:
  production: false
  development: true

server:
  graphql:
    deployment:
      name: graphql-deployment
      replicaCount: 1
      image:
        repository: iknowhtml/todo-graphql
        tag: latest
      imagePullPolicy: ifNotPresent
    clusterIPService:
      name: graphql-cluster-ip-service
    port: 9090

postgresql:
  postgresqlUsername: user
  postgresqlPassword: password
  postgresqlDatabase: todo
  initdbScripts:
    initdb.sql: |
      CREATE TABLE tasks
      (
        id serial,
        name text NOT NULL,
        completed boolean NOT NULL DEFAULT false,
        description text,
        due_date date,
        due_time time with time zone,
        location point,
        CONSTRAINT id_pk PRIMARY KEY (id)
      );