environment:
  production: false
  development: true

server:
  graphql:
    deployment:
      name: graphql
      replicaCount: 1
      image:
        repository: iknowhtml/todo-graphql
        tag: latest
      imagePullPolicy: IfNotPresent
    clusterIPService:
      name: graphql-cluster-ip
    port: 9090
    tokenSecret: "SUPER_SECRET_TOKEN"

postgresql:
  postgresqlUsername: postgres
  postgresqlPassword: password
  initdbUsername: postgres
  initdbPassword: password
  postgresqlDatabase: todo
  initdbScripts:
    setup.sql: |
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

      CREATE TABLE tasks
      (
        id uuid NOT NULL DEFAULT uuid_generate_v4(),
        name text NOT NULL,
        completed boolean NOT NULL DEFAULT false,
        description text,
        due_date date,
        due_time time with time zone,
        location point,
        CONSTRAINT id_pk PRIMARY KEY (id)
      );

      INSERT INTO tasks (name, description)
      VALUES ('task 1', 'description 1');

      INSERT INTO tasks (name, description)
      VALUES ('task 2', 'description 2');

      INSERT INTO tasks (name, description)
      VALUES ('task 3', 'description 3');