environment:
  production: false
  development: true

server:
  graphql:
    deployment:
      name: graphql-deployment
      replicaCount: 1
      imageRepository: iknowhtml/todo-graphql
      imageTag: latest
      imagePullPolicy: IfNotPresent
      jwtSecret: "SUPER_SECRET_TOKEN"
    service:
      name: graphql-cluster-ip
    port: 9090

postgresql:
  postgresqlUsername: postgres
  postgresqlPassword: password
  initdbUsername: postgres
  initdbPassword: password
  postgresqlDatabase: todo
  initdbScripts:
    setup.sql: |
      CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

      CREATE TABLE users
      (
        id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
        username text NOT NULL UNIQUE,
        password_hash text NOT NULL,
        email text NOT NULL UNIQUE,
        first_name text,
        last_name text
      );

      CREATE TABLE tasks
      (
        id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
        name text NOT NULL,
        author_id uuid NOT NULL REFERENCES users(id),
        completed boolean NOT NULL DEFAULT false,
        description text,
        due_date date,
        due_time time with time zone,
        location point
      );

      INSERT INTO users(id, username, password_hash, email) 
      VALUES ('144d41c8-ee9b-45ef-9bc5-b1e72295cd52', 'user', '$2b$10$rOW479moLEkWG3Gk5sESaOjXfy.go1EiMQ1mZfsZN0MfuH/0.0XXa', 'email@domain.com');

      INSERT INTO tasks(name, author_id) 
      VALUES('task 1', '144d41c8-ee9b-45ef-9bc5-b1e72295cd52');

      INSERT INTO tasks(name, author_id) 
      VALUES('task 2', '144d41c8-ee9b-45ef-9bc5-b1e72295cd52');
      
      INSERT INTO tasks(name, author_id) 
      VALUES('task 3', '144d41c8-ee9b-45ef-9bc5-b1e72295cd52');